name: Run Scraper

on:
  schedule:
    - cron: "0 */4 * * *"   # каждые 4 часа
  workflow_dispatch:        # запуск вручную через GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome & chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Run scraper
        run: python scraper.py
        env:
          COPART_USER: ${{ secrets.COPART_USER }}
          COPART_PASS: ${{ secrets.COPART_PASS }}
          FLASK_CLEAR_URL: ${{ secrets.FLASK_CLEAR_URL }}
          FLASK_UPLOAD_URL: ${{ secrets.FLASK_UPLOAD_URL }}
